name = input("กรอกชื่อ\n")
nickname = input("ชื่อเล่น\n")
age = input("อายุ\n")
id = input("รหัสประจำตัว")
study = input("ชั้นปี")
height = input("ส่วนสูง")
weight = input("น้ำหนัก")
num = height + weight
print ("ประวัติโดยย่อ")
print (f'ชื่อ : {name} อายุ : {age} ปี')
print (f'รหัสประจำตัว : {id} ชั้นปี : {study}')
print (f'ชื่อเล่น : {nickname}')
print (f'ส่วนสูง : {height} น้ำหนัก : {weight}')
print (f'ส่วนสูง + น้ำหนัก = {num} ')